cask_args appdir: '/Applications'

tap 'hashicorp/tap'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/core'

# brew
brew 'fzf'
brew "ghq"
brew 'jq'
brew 'node'
brew 'neovim'
brew 'peco'
brew 'pwgen'
brew 'python-yq'
brew 'terraform'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'hashicorp/tap/terraform-ls'
brew 'ripgrep'
brew 'starship'
brew 'sheldon'
brew 'rust'

# cask
cask 'contexts'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'karabiner-elements'
cask 'raycast'
cask 'rectangle'
cask 'vivaldi'
cask 'visual-studio-code'
cask 'font-hack-nerd-font'
cask 'google-drive'
cask 'drawio'

# vscode
vscode "MS-CEINTL.vscode-language-pack-ja"
