# Inserts a blank line between shell prompts
add_newline = true

format = """\
  $hostname\
  $directory\
  $custom\
  $line_break\
  $jobs\
  $battery\
  $time\
  $username\
  $character\
  """

right_format = """\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  """

[directory]
style = 'cyan'

[hostname]
ssh_only = false
style = 'green'

[username]
show_always = true
style_user = 'yellow'
format = '[$user]($style) '
