# Inserts a blank line between shell prompts
add_newline = true

format = """\
  $env_var\
  $hostname\
  $directory\
  $line_break\
  $custom\
  $jobs\
  $battery\
  $time\
  $username\
  $character\
  """

right_format = """\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  """

[directory]
style = 'cyan'
truncation_length = 7
truncate_to_repo = false

[env_var.OS_CLOUD]
style = 'dimmed red'
variable = 'OS_CLOUD'
format = "[\\[$env_value\\]]($style) \n"

[hostname]
ssh_only = false
style = 'green'

[username]
show_always = true
style_user = 'yellow'
format = '[$user]($style) '
