# Inserts a blank line between shell prompts
add_newline = true

format = """\
  $env_var\
  $kubernetes\
  $line_break\
  $hostname\
  $directory\
  $line_break\
  $custom\
  $jobs\
  $username\
  $character\
  """

right_format = """\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  """

[directory]
style = 'cyan'
truncation_length = 10
truncate_to_repo = false

[env_var.OS_CLOUD]
# https://www.color-sample.com/colors/721c06/
style = '#721C06'
variable = 'OS_CLOUD'
format = "[\\[$env_value\\]]($style) \n"

[env_var.CURRENT_BP_CONTEXT]
# https://www.color-sample.com/colors/065b70/
style = '#065B70'
variable = 'CURRENT_BP_CONTEXT'
format = "[\\[bp ctx: $env_value\\]]($style)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[hostname]
ssh_only = false
style = 'green'

[kubernetes]
format = '[\[⛵ $context\]](dimmed green) '
disabled = false

[username]
show_always = true
style_user = 'yellow'
format = '[$user]($style) '
