name: 'macos'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: 'test'
    runs-on: macos-latest
    environment: staging

    # Use the zsh shell
    defaults:
      run:
        shell: zsh {0}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: make install
